### ISSUE TITLE
`rustc nightly-2023-07-09` has some aggressive changes that failed many `kmir-parse` test cases

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics-compiletest#3]
With the `ui` test suite synced up with the current rest-lang repo, we compile the test suite to MIR using two different versions of rustc and tested on `kmir parse`. The results are very different:
1. With `1.72.0-nightly (46514218f 2023-06-20)`, 2550 test cases are generated, with `1520 failed, 1030 passed`
2. With `rustc 1.72.0-nightly (83964c156 2023-07-08)`, 2550 test cases are generaed, with `2134 failed, 416 passed`. 
> note that 
> 1. the exact version of `rustc 1.72.0-nightly (839e9a6e1 2023-07-09)` is not obtainable, not sure why.
> 2. all tested on `x86_64-unknown-linux-gnu` target

I am suspecting there are aggressive changes in the MIR syntax in the latest version. 
It is preferred to roll back to 1.72.0-nightly (46514218f 2023-06-20).

**Comment by dkcumming** [comment]
@yanliu18 Now that the PR is merged is this okay to close?
